AppBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastname:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        reservationDate:
            type: date
            column: reservation_date
        ticketType:
            type: boolean
            column: ticket_type
        tariff:
            type: boolean
            length: 255
        birthdate:
            type: date
        country:
            type: string
            length: 255
    lifecycleCallbacks: {  }
